#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FlagMySpace.Droid.Resource", IsApplication=true)]

namespace FlagMySpace.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Acr.UserDialogs.Resource.Attribute.ahBarColor = global::FlagMySpace.Droid.Resource.Attribute.ahBarColor;
			global::Acr.UserDialogs.Resource.Attribute.ahBarLength = global::FlagMySpace.Droid.Resource.Attribute.ahBarLength;
			global::Acr.UserDialogs.Resource.Attribute.ahBarWidth = global::FlagMySpace.Droid.Resource.Attribute.ahBarWidth;
			global::Acr.UserDialogs.Resource.Attribute.ahCircleColor = global::FlagMySpace.Droid.Resource.Attribute.ahCircleColor;
			global::Acr.UserDialogs.Resource.Attribute.ahDelayMillis = global::FlagMySpace.Droid.Resource.Attribute.ahDelayMillis;
			global::Acr.UserDialogs.Resource.Attribute.ahRadius = global::FlagMySpace.Droid.Resource.Attribute.ahRadius;
			global::Acr.UserDialogs.Resource.Attribute.ahRimColor = global::FlagMySpace.Droid.Resource.Attribute.ahRimColor;
			global::Acr.UserDialogs.Resource.Attribute.ahRimWidth = global::FlagMySpace.Droid.Resource.Attribute.ahRimWidth;
			global::Acr.UserDialogs.Resource.Attribute.ahSpinSpeed = global::FlagMySpace.Droid.Resource.Attribute.ahSpinSpeed;
			global::Acr.UserDialogs.Resource.Attribute.ahText = global::FlagMySpace.Droid.Resource.Attribute.ahText;
			global::Acr.UserDialogs.Resource.Attribute.ahTextColor = global::FlagMySpace.Droid.Resource.Attribute.ahTextColor;
			global::Acr.UserDialogs.Resource.Attribute.ahTextSize = global::FlagMySpace.Droid.Resource.Attribute.ahTextSize;
			global::Acr.UserDialogs.Resource.Drawable.ic_errorstatus = global::FlagMySpace.Droid.Resource.Drawable.ic_errorstatus;
			global::Acr.UserDialogs.Resource.Drawable.ic_successstatus = global::FlagMySpace.Droid.Resource.Drawable.ic_successstatus;
			global::Acr.UserDialogs.Resource.Drawable.roundedbg = global::FlagMySpace.Droid.Resource.Drawable.roundedbg;
			global::Acr.UserDialogs.Resource.Drawable.roundedbgdark = global::FlagMySpace.Droid.Resource.Drawable.roundedbgdark;
			global::Acr.UserDialogs.Resource.Id.loadingImage = global::FlagMySpace.Droid.Resource.Id.loadingImage;
			global::Acr.UserDialogs.Resource.Id.loadingProgressBar = global::FlagMySpace.Droid.Resource.Id.loadingProgressBar;
			global::Acr.UserDialogs.Resource.Id.loadingProgressWheel = global::FlagMySpace.Droid.Resource.Id.loadingProgressWheel;
			global::Acr.UserDialogs.Resource.Id.textViewStatus = global::FlagMySpace.Droid.Resource.Id.textViewStatus;
			global::Acr.UserDialogs.Resource.Layout.loading = global::FlagMySpace.Droid.Resource.Layout.loading;
			global::Acr.UserDialogs.Resource.Layout.loadingimage = global::FlagMySpace.Droid.Resource.Layout.loadingimage;
			global::Acr.UserDialogs.Resource.Layout.loadingprogress = global::FlagMySpace.Droid.Resource.Layout.loadingprogress;
			global::Acr.UserDialogs.Resource.String.ApplicationName = global::FlagMySpace.Droid.Resource.String.ApplicationName;
			global::Acr.UserDialogs.Resource.String.Hello = global::FlagMySpace.Droid.Resource.String.Hello;
			global::Acr.UserDialogs.Resource.String.library_name = global::FlagMySpace.Droid.Resource.String.library_name;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarColor = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarLength = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarWidth = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahCircleColor = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahDelayMillis = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRadius = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRimColor = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRimWidth = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahText = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahTextColor = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahTextSize = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::FlagMySpace.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::FlagMySpace.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::FlagMySpace.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::FlagMySpace.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::FlagMySpace.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::FlagMySpace.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::FlagMySpace.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::FlagMySpace.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::FlagMySpace.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::FlagMySpace.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::FlagMySpace.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::FlagMySpace.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::FlagMySpace.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::FlagMySpace.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::FlagMySpace.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::FlagMySpace.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::FlagMySpace.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::FlagMySpace.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::FlagMySpace.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::FlagMySpace.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::FlagMySpace.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::FlagMySpace.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::FlagMySpace.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::FlagMySpace.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::FlagMySpace.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::FlagMySpace.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::FlagMySpace.Droid.Resource.String.Hello;
			global::XLabs.Forms.Resource.Color.calendar_active_month_bg = global::FlagMySpace.Droid.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_bg = global::FlagMySpace.Droid.Resource.Color.calendar_bg;
			global::XLabs.Forms.Resource.Color.calendar_divider = global::FlagMySpace.Droid.Resource.Color.calendar_divider;
			global::XLabs.Forms.Resource.Color.calendar_highlighted_day_bg = global::FlagMySpace.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_inactive_month_bg = global::FlagMySpace.Droid.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_day_bg = global::FlagMySpace.Droid.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_range_bg = global::FlagMySpace.Droid.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Resource.Color.calendar_text_active = global::FlagMySpace.Droid.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Resource.Color.calendar_text_inactive = global::FlagMySpace.Droid.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Resource.Color.calendar_text_selected = global::FlagMySpace.Droid.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Resource.Color.calendar_text_selector = global::FlagMySpace.Droid.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Resource.Color.calendar_text_unselectable = global::FlagMySpace.Droid.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Resource.Dimension.calendar_day_headers_paddingbottom = global::FlagMySpace.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Resource.Dimension.calendar_month_title_bottommargin = global::FlagMySpace.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Resource.Dimension.calendar_month_topmargin = global::FlagMySpace.Droid.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Resource.Dimension.calendar_text_medium = global::FlagMySpace.Droid.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Resource.Dimension.calendar_text_small = global::FlagMySpace.Droid.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Resource.Drawable.ad16 = global::FlagMySpace.Droid.Resource.Drawable.ad16;
			global::XLabs.Forms.Resource.Drawable.calendar_bg_selector = global::FlagMySpace.Droid.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Resource.Id.calendar_grid = global::FlagMySpace.Droid.Resource.Id.calendar_grid;
			global::XLabs.Forms.Resource.Id.calendar_view = global::FlagMySpace.Droid.Resource.Id.calendar_view;
			global::XLabs.Forms.Resource.Id.left_arrow = global::FlagMySpace.Droid.Resource.Id.left_arrow;
			global::XLabs.Forms.Resource.Id.right_arrow = global::FlagMySpace.Droid.Resource.Id.right_arrow;
			global::XLabs.Forms.Resource.Id.title = global::FlagMySpace.Droid.Resource.Id.title;
			global::XLabs.Forms.Resource.Layout.calendar_pager_layout = global::FlagMySpace.Droid.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Resource.Layout.calendar_picker = global::FlagMySpace.Droid.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Resource.Layout.dialog = global::FlagMySpace.Droid.Resource.Layout.dialog;
			global::XLabs.Forms.Resource.Layout.month = global::FlagMySpace.Droid.Resource.Layout.month;
			global::XLabs.Forms.Resource.Layout.week = global::FlagMySpace.Droid.Resource.Layout.week;
			global::XLabs.Forms.Resource.String.ApplicationName = global::FlagMySpace.Droid.Resource.String.ApplicationName;
			global::XLabs.Forms.Resource.String.Hello = global::FlagMySpace.Droid.Resource.String.Hello;
			global::XLabs.Forms.Resource.String.day_name_format = global::FlagMySpace.Droid.Resource.String.day_name_format;
			global::XLabs.Forms.Resource.String.full_date_format = global::FlagMySpace.Droid.Resource.String.full_date_format;
			global::XLabs.Forms.Resource.String.invalid_date = global::FlagMySpace.Droid.Resource.String.invalid_date;
			global::XLabs.Forms.Resource.String.library_name = global::FlagMySpace.Droid.Resource.String.library_name;
			global::XLabs.Forms.Resource.String.month_name_format = global::FlagMySpace.Droid.Resource.String.month_name_format;
			global::XLabs.Forms.Resource.Style.CalendarCell = global::FlagMySpace.Droid.Resource.Style.CalendarCell;
			global::XLabs.Forms.Resource.Style.CalendarCell_CalendarDate = global::FlagMySpace.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Resource.Style.CalendarCell_DayHeader = global::FlagMySpace.Droid.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Resource.Style.CalendarTitle = global::FlagMySpace.Droid.Resource.Style.CalendarTitle;
			global::XLabs.Platform.Resource.String.ApplicationName = global::FlagMySpace.Droid.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::FlagMySpace.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_active_month_bg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int calendar_bg = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int calendar_divider = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int calendar_highlighted_day_bg = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int calendar_inactive_month_bg = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_selected_day_bg = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int calendar_selected_range_bg = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int calendar_text_active = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int calendar_text_inactive = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int calendar_text_selected = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int calendar_text_selector = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int calendar_text_unselectable = 2131034122;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_day_headers_paddingbottom = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int calendar_month_title_bottommargin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int calendar_month_topmargin = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int calendar_text_medium = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_text_small = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar_bg_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_errorstatus = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_successstatus = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int roundedbg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int roundedbgdark = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080008
			public const int calendar_grid = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int calendar_view = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int left_arrow = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int loadingImage = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int loadingProgressBar = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int loadingProgressWheel = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int right_arrow = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int textViewStatus = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int title = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loading = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loadingimage = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int loadingprogress = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int month = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int week = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int day_name_format = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int full_date_format = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int invalid_date = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int month_name_format = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
